### ISSUE TITLE
Tooltips get removed from DOM after png download

### ISSUE THREAD

**Issue by akanshat** [JuanIrache/d3-svg-to-png#12]
I added a tooltip to the SVG which is otherwise hidden and on mouseover, the visibility is set to "visible". This tooltip works fine until the SVG is exported as a png. I noticed that the HTML I added to the tooltip is removed from DOM itself.

> It can also rescale the svg image, ignore certain DOM elements...
It is maybe because these are ignored as a part of this package.

**Comment by JuanIrache** [comment]
Hi, sorry for my late reply. Somehow I didn't get a notification for this. I don't know when I'll have the time to implement this. If anyone can provide  a PR, it is very welcome.
